name: CI
on: pull_request
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Validate witx
        run: cargo run --manifest-path=validate-witx/Cargo.toml ./compute-at-edge.witx
